### ISSUE TITLE
default branch name – consistency with related repo

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-ontologies#1]
In GitLab by @koeaw on Apr 19, 2022, 11:04

I was wondering if it would make sense to rename the default branch of the repository from `master` to `main` for consistency (since `main` is also the default name used by [APIS RDF Devops](https://gitlab.com/acdh-oeaw/apis/apis-rdf-devops), and generally the recommended default branch name these days).

For some reason, the branch is actually already called that on my local copy, but I'm assuming I must have renamed it myself rather than the name having changed on here (?!).

**Comment by koeaw** [comment]
Not applicable anymore since the branch in question was given the suggested name during import of the repository to GitHub -> closing.
