### ISSUE TITLE
"app__name" variable in ontologies apps unclear

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-ontologies#39]
While updating branches of mine which contain (WIP) refactorings I came across this variable again, which exists in the `__init__.py` files of several Ontologies apps.

Is `app__name`:
1. a misspelled version of `app_name` (meant to be used in `urls.py`)? or
2. a (wonky) duplicate effort of what `name` does in `apps.py`? or
3. a legitimate variable?

Example for 1. is found in in `webpage/urls.py`:
```python
app_name = 'webpage'
```

Example for 2. is found in `apps.py` of any Ontologies project:
```python
class ApisOntologyConfig(AppConfig):
    name = 'apis_ontology'
```

(Side note: these should be updated to double quotation marks sometime.)

**Comment by steffres** [comment]
I had added it for experimentational wiring of ontologies into core. I don't remember if it does anything, or if its usage might have been replaced by something else. It would need to be tested if removal of it breaks anything.
