### ISSUE TITLE
Adapt settings template for bibsonomy plugin, document settings

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-ontologies#42]
The original template for Bibsonomy settings is [very rudimentary](https://github.com/acdh-oeaw/apis-ontologies/blob/main/example_project/settings/local_settings_template.py#L30), e.g. doesn't consider setting of access keys via CI/CD variables. – Reason why we couldn't make use of it as-is and ended up accessing Zotero differently for our import scripts.

I just saw that SicProd uses an [adapted form](https://github.com/acdh-oeaw/apis-ontologies/blob/main/sicprod/settings/server_settings.py#L26) of the original settings, though it's still unclear to me how those would be transposed to Zotero. Like, what is the `group` setting (and why is it hardcoded)? For Zotero, we pass two different values, both of which are stored as CI/CD secrets.

What needs doing is:

- [ ] update existing settings in `local_settings_template.py` to allow the use of env variables
- [ ] document how to use the plugin with either Zotero or Bibsonomy (via comments right there in the template? And/or in the repo's README? And/or via actual documentation?)

**Comment by b1rger** [comment]
I think all documentation regarding how to use the bibsonomy app should be done in the bibsonomy repository.

**Comment by koeaw** [comment]
> I think all documentation regarding how to use the bibsonomy app should be done in the bibsonomy repository.

Makes sense. So actually, what's currently in `example_project/settings/local_settings_template.py` should get removed/moved.
