### ISSUE TITLE
Draft: add files for example project to base new APIS Ontologies apps on - [opened]

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-ontologies#6]
In GitLab by @koeaw  on Aug 3, 2022, 15:06

_Merges kk/feat_example_project -> dev_

Separates out commits for example project originally submitted via !1.

Files added to example project are based on files of existing APIS Ontologies apps, esp. Jelinek. A number of files were updated primarily with regard to formatting, but partly (minimally) also content-wise: e.g. protocol portions of URLs were changed from `http` to `https` throughout (_without_ having tested they work; it is assumed that in 2022, public databases can be queried securely).

`server_settings.py` was refactored significantly with regard to structure/formatting, code comments, partly also default values, but likely needs to be modified further:
* all settings should be documented (README?)
* generic default values (or no values) should be used wherever possible,
* keys/secrets ought to be removed (and instructions on how to set them locally or via CI/CD added),
* any missing settings/variables of potential interest to devs should get (re)added and documented, e.g. values inherited from `base.py` which devs may want to override or add to.

`models.py` is very bare-bones and should have a few example entities/relationships added to it.

**Comment by koeaw** [comment]
This was converted to a draft pull request: #7
